[TextBox]
rectangle_colour = [0, 0, 0, 1]
text_colour = [1, 1, 1, 1]
font_size = 20
line_gap = 10
rectangle = { pos = { x = 1.0, y = 20.0 }, size = { x = 30.0, y = 11.0 }}

[SpeakerBox]
rectangle_colour = [0, 0, 0, 1]
text_colour = [1, 1, 1, 1]
font_size = 18
padding = [0.3, 0.0, 0.05, 0.05]
[SpeakerBox.rectangle]
pos = { x = 1.0, y = 18.5 }
size = { x = 10.0, y = 1.5 }