[package]
name = "example_vn"
version = "0.2.0"
authors = ["Hiruna Jayamanne <hirunav2@gmail.com>"]

[dependencies]
piston_window = "*"
gfx_glyph = "*"
gfx_device_gl = "*"

[dependencies.gobu]
path = "../gobu"
features = ["gfx_glyph_text"]
