[TextBox]
rectangle_colour = [0, 0, 0, 1]
text_colour = [1, 1, 1, 1]
font_size = 20
line_gap = 10
rectangle = {x = 1.0, y = 20.0, w = 30.0, h = 11.0}

[SpeakerBox]
rectangle_colour = [0, 0, 0, 1]
text_colour = [1, 1, 1, 1]
font_size = 18
rectangle = {x = 1.0, y = 18.5, w = 10.0, h = 1.5}
padding = [0.05, 0.3]